In [4]:
import pandas as pd
from scipy.stats import kendalltau

# Load the dataset
df = pd.read_csv("kendall_tau_results")
df

,Unnamed: 0,site_id,species_a,phenophase_a,species_b,phenophase_b,number_of_observations,kendall_tau,p_value
0,0,8180,444,483,444,498,13,-0.526361,0.013950
1,1,8181,444,483,444,498,13,0.091521,0.667584
2,2,8182,3,371,3,467,14,0.333333,0.107792
3,3,8182,3,371,3,483,14,0.329567,0.109187
4,4,8182,3,371,3,500,14,0.205718,0.319392
...,...,...,...,...,...,...,...,...,...
1389,1389,17582,61,467,1212,467,10,0.022222,1.000000
1390,1390,17582,61,483,82,483,11,0.462963,0.050225
1391,1391,17582,61,483,1212,483,11,0.537037,0.023127
1392,1392,17582,82,467,1212,467,10,0.022222,1.000000
1393,1393,17582,82,483,1212,483,11,0.277778,0.240065

In [5]:
# Remove rows where species_a and species_b are the same
filtered_df = df[df['species_a'] != df['species_b']]
filtered_df

,Unnamed: 0,site_id,species_a,phenophase_a,species_b,phenophase_b,number_of_observations,kendall_tau,p_value
5,5,8182,3,371,28,371,14,0.205718,0.319392
6,6,8182,3,371,28,467,14,0.000000,1.000000
7,7,8182,3,371,28,483,14,0.079551,0.699012
8,8,8182,3,371,93,371,14,0.057471,0.781787
9,9,8182,3,371,93,483,14,0.091954,0.657631
...,...,...,...,...,...,...,...,...,...
1389,1389,17582,61,467,1212,467,10,0.022222,1.000000
1390,1390,17582,61,483,82,483,11,0.462963,0.050225
1391,1391,17582,61,483,1212,483,11,0.537037,0.023127
1392,1392,17582,82,467,1212,467,10,0.022222,1.000000
1393,1393,17582,82,483,1212,483,11,0.277778,0.240065

In [6]:
significant_df = filtered_df[filtered_df["p_value"] <= 0.05]
significant_df

,Unnamed: 0,site_id,species_a,phenophase_a,species_b,phenophase_b,number_of_observations,kendall_tau,p_value
14,14,8182,3,371,1172,467,14,0.411435,0.046435
28,28,8182,3,467,102,371,14,0.514294,0.012709
34,34,8182,3,467,1172,500,14,0.443210,0.031051
36,36,8182,3,467,1174,371,14,0.483268,0.017756
41,41,8182,3,471,93,498,13,0.431382,0.042916
...,...,...,...,...,...,...,...,...,...
1363,1363,12003,3,498,98,498,12,0.558156,0.012918
1365,1365,12003,12,467,98,371,11,0.537037,0.023127
1382,1382,17582,3,483,61,483,11,0.629630,0.007746
1388,1388,17582,61,467,82,467,10,0.555556,0.028609
1391,1391,17582,61,483,1212,483,11,0.537037,0.023127

In [7]:
pairs = pd.read_csv("valid_pairs")
pairs

,Unnamed: 0,site_id,species_a,phenophase_a,species_b,phenophase_b,matching_years,first_yes_days_a,first_yes_days_b
0,0,8180,444,483,444,498,"[2012, 2013, 2014, 2015, 2016, 2017, 2018, 201...","[3, 24, 29, 17, 18, 17, 2, 22, 10, 15, 6, 6, 10]","[26, 4, 1, 8, 26, 14, 28, 16, 30, 13, 31, 18, 10]"
1,1,8181,444,483,444,498,"[2012, 2013, 2014, 2015, 2016, 2017, 2018, 201...","[3, 24, 29, 17, 18, 17, 30, 22, 10, 15, 18, 6, 3]","[30, 4, 22, 24, 20, 6, 28, 5, 14, 13, 31, 1, 10]"
2,2,8182,3,371,3,467,"[2011, 2012, 2013, 2014, 2015, 2016, 2017, 201...","[4, 3, 9, 21, 13, 27, 27, 18, 1, 12, 4, 3, 21,...","[4, 27, 10, 6, 27, 27, 3, 14, 1, 7, 5, 3, 25, 17]"
3,3,8182,3,371,3,483,"[2011, 2012, 2013, 2014, 2015, 2016, 2017, 201...","[4, 3, 9, 21, 13, 27, 27, 18, 1, 12, 4, 3, 21,...","[4, 27, 10, 6, 23, 27, 3, 14, 1, 7, 5, 3, 18, 17]"
4,4,8182,3,371,3,500,"[2011, 2012, 2013, 2014, 2015, 2016, 2017, 201...","[4, 3, 9, 21, 13, 27, 27, 18, 1, 12, 4, 3, 21,...","[6, 16, 9, 16, 13, 25, 29, 11, 13, 24, 29, 30,..."
...,...,...,...,...,...,...,...,...,...
1389,1389,17582,61,467,1212,467,"[2015, 2016, 2017, 2018, 2019, 2020, 2021, 202...","[13, 14, 9, 16, 17, 7, 6, 11, 10, 12]","[28, 6, 9, 1, 17, 7, 11, 19, 10, 18]"
1390,1390,17582,61,483,82,483,"[2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...","[30, 13, 6, 9, 16, 17, 7, 11, 11, 10, 12]","[16, 13, 6, 9, 16, 17, 7, 28, 1, 8, 30]"
1391,1391,17582,61,483,1212,483,"[2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...","[30, 13, 6, 9, 16, 17, 7, 11, 11, 10, 12]","[30, 13, 1, 9, 1, 17, 7, 11, 19, 10, 18]"
1392,1392,17582,82,467,1212,467,"[2015, 2016, 2017, 2018, 2019, 2020, 2021, 202...","[13, 6, 9, 16, 17, 7, 2, 1, 8, 12]","[28, 6, 9, 1, 17, 7, 11, 19, 10, 18]"
1393,1393,17582,82,483,1212,483,"[2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...","[16, 13, 6, 9, 16, 17, 7, 28, 1, 8, 30]","[30, 13, 1, 9, 1, 17, 7, 11, 19, 10, 18]"

In [8]:
filtered_pairs = df[df['species_a'] != df['species_b']]
filtered_pairs

,Unnamed: 0,site_id,species_a,phenophase_a,species_b,phenophase_b,number_of_observations,kendall_tau,p_value
5,5,8182,3,371,28,371,14,0.205718,0.319392
6,6,8182,3,371,28,467,14,0.000000,1.000000
7,7,8182,3,371,28,483,14,0.079551,0.699012
8,8,8182,3,371,93,371,14,0.057471,0.781787
9,9,8182,3,371,93,483,14,0.091954,0.657631
...,...,...,...,...,...,...,...,...,...
1389,1389,17582,61,467,1212,467,10,0.022222,1.000000
1390,1390,17582,61,483,82,483,11,0.462963,0.050225
1391,1391,17582,61,483,1212,483,11,0.537037,0.023127
1392,1392,17582,82,467,1212,467,10,0.022222,1.000000
1393,1393,17582,82,483,1212,483,11,0.277778,0.240065

In [9]:
# Function to calculate unique species pairs and counts by site
def calculate_species_counts_by_site(df):
    # Group by site
    grouped = df.groupby('site_id')
    site_results = {}

    for site_id, group in grouped:
        # Create a set of unique species pairs for the site
        unique_pairs = group.apply(
            lambda row: tuple(sorted([row['species_a'], row['species_b']])), axis=1
        ).drop_duplicates()

        # Count occurrences of each species in unique pairs
        species_counts = pd.Series(
            [species for pair in unique_pairs for species in pair]
        ).value_counts()

        # Create a new DataFrame for the site's results
        species_counts_df = species_counts.reset_index()
        species_counts_df.columns = ['species', 'observed']

        # Store the results for this site
        site_results[site_id] = species_counts_df

    return site_results

# Example usage
site_species_counts = calculate_species_counts_by_site(significant_df)

# Display the results for each site
for site_id, counts_df in site_species_counts.items():
    print(f"Site ID: {site_id}")
    print(counts_df)
    print("\n" + "-"*40 + "\n")

Site ID: 8182
   species  observed
0   1172.0         5
1     93.0         5
2      3.0         4
3    102.0         4
4   1174.0         4
5     28.0         2

----------------------------------------

Site ID: 8806
   species  observed
0     81.0         6
1     12.0         5
2    823.0         5
3   1192.0         5
4     82.0         4
5     61.0         4
6      3.0         3
7    100.0         2

----------------------------------------

Site ID: 8836
   species  observed
0      3.0         3
1     81.0         3
2     82.0         3
3    823.0         3

----------------------------------------

Site ID: 8899
   species  observed
0     61.0         3
1     79.0         3
2   1172.0         3
3   1174.0         3

----------------------------------------

Site ID: 8901
   species  observed
0     91.0         3
1   1199.0         3
2     97.0         3
3   1189.0         3

----------------------------------------

Site ID: 8902
   species  observed
0      3.0         4
1     68.0         3
2    102.0         3
3   1187.0         3
4     12.0         1

----------------------------------------

Site ID: 8903
   species  observed
0     12.0         2
1     79.0         2
2    100.0         2

----------------------------------------

Site ID: 8904
   species  observed
0     28.0         2
1   1172.0         1
2     93.0         1

----------------------------------------

Site ID: 9338
   species  observed
0      3.0         7
1     98.0         7
2    970.0         7
3   1192.0         7
4     76.0         5
5    941.0         5
6   1187.0         5
7     81.0         4
8     60.0         4
9    823.0         3

----------------------------------------

Site ID: 9339
   species  observed
0      3.0         6
1     60.0         6
2    823.0         6
3   1181.0         5
4     82.0         5
5     61.0         4
6     98.0         4
7     93.0         4
8   1172.0         3
9   1184.0         3

----------------------------------------

Site ID: 9340
   species  observed
0    102.0         3
1      3.0         1
2   1187.0         1
3   1212.0         1

----------------------------------------

Site ID: 9341
    species  observed
0      67.0         9
1     102.0         8
2    1019.0         8
3    1179.0         7
4      12.0         7
5       3.0         6
6      60.0         6
7      61.0         6
8    1181.0         6
9      93.0         5
10     74.0         5
11     81.0         4
12      7.0         3

----------------------------------------

Site ID: 9342
   species  observed
0    100.0         3
1      3.0         2
2   1159.0         2
3   1187.0         2
4     67.0         1

----------------------------------------

Site ID: 9343
    species  observed
0     970.0         7
1    1172.0         6
2     823.0         6
3       3.0         5
4      82.0         5
5    1179.0         5
6      98.0         4
7      79.0         3
8       7.0         2
9      81.0         2
10     93.0         1

----------------------------------------

Site ID: 11895
   species  observed
0     97.0         4
1    970.0         4
2   1172.0         4
3     82.0         3
4     98.0         3

----------------------------------------

Site ID: 11896
   species  observed
0    100.0         3
1      3.0         2
2   1187.0         2
3    941.0         2
4   1177.0         1

----------------------------------------

Site ID: 11897
   species  observed
0      3.0         1
1     82.0         1

----------------------------------------

Site ID: 11899
   species  observed
0      3.0         2
1     60.0         2
2   1181.0         2

----------------------------------------

Site ID: 12002
   species  observed
0    941.0         1
1   1159.0         1

----------------------------------------

Site ID: 12003
   species  observed
0      3.0         2
1     98.0         2
2     82.0         1
3     12.0         1

----------------------------------------

Site ID: 17582
   species  observed
0     61.0         3
1      3.0         1
2     82.0         1
3   1212.0         1

----------------------------------------

In [10]:
def calculate_species_counts_by_site_as_dataframe(df):
    # Create an empty list to store results
    all_sites_data = []

    # Group by site
    grouped = df.groupby('site_id')

    for site_id, group in grouped:
        # Create a set of unique species pairs for the site
        unique_pairs = group.apply(
            lambda row: tuple(sorted([row['species_a'], row['species_b']])), axis=1
        ).drop_duplicates()

        # Count occurrences of each species in unique pairs
        species_counts = pd.Series(
            [species for pair in unique_pairs for species in pair]
        ).value_counts()

        # Create a DataFrame for this site's results
        species_counts_df = species_counts.reset_index()
        species_counts_df.columns = ['species', 'observed']
        species_counts_df['site_id'] = site_id  # Add site_id as a column

        # Append to the list
        all_sites_data.append(species_counts_df)

    # Combine all site results into a single DataFrame
    return pd.concat(all_sites_data, ignore_index=True)

# Example usage
site_species_counts_df = calculate_species_counts_by_site_as_dataframe(significant_df)

# Display the combined DataFrame
print(site_species_counts_df)

     species  observed  site_id
0     1172.0         5     8182
1       93.0         5     8182
2        3.0         4     8182
3      102.0         4     8182
4     1174.0         4     8182
..       ...       ...      ...
110     12.0         1    12003
111     61.0         3    17582
112      3.0         1    17582
113     82.0         1    17582
114   1212.0         1    17582

[115 rows x 3 columns]

In [11]:
# Step 1: Create the `raw_expected` counts for each site
def calculate_raw_expected_per_site(df):
    # Create an empty list to store results
    all_sites_data = []

    # Group by site
    grouped = df.groupby('site_id')

    for site_id, group in grouped:
        # Create unique species pairs (ignoring phenophases) for the site
        group['species_pair'] = group.apply(
            lambda row: tuple(sorted([row['species_a'], row['species_b']])), axis=1
        )
        unique_pairs = group.drop_duplicates(subset=['species_pair'])

        # Count occurrences of each species in unique pairs
        species_counts = pd.concat([
            unique_pairs['species_a'],
            unique_pairs['species_b']
        ]).value_counts().reset_index()

        species_counts.columns = ['species', 'raw_expected']
        species_counts['site_id'] = site_id  # Add site_id as a column

        # Append the results to the list
        all_sites_data.append(species_counts)

    # Combine all site results into a single DataFrame
    return pd.concat(all_sites_data, ignore_index=True)

# Step 2: Calculate `raw_expected` for each site
raw_expected_per_site = calculate_raw_expected_per_site(filtered_pairs)

# Step 3: Merge the `raw_expected` column with the observed results
merged_results = site_species_counts_df.merge(
    raw_expected_per_site, on=['site_id', 'species'], how='left'
)

# Display the final DataFrame
pd.set_option('display.max_rows', None)  # Show all rows
print(merged_results)

     species  observed  site_id  raw_expected
0     1172.0         5     8182             5
1       93.0         5     8182             5
2        3.0         4     8182             5
3      102.0         4     8182             5
4     1174.0         4     8182             5
5       28.0         2     8182             5
6       81.0         6     8806             7
7       12.0         5     8806             7
8      823.0         5     8806             7
9     1192.0         5     8806             7
10      82.0         4     8806             7
11      61.0         4     8806             7
12       3.0         3     8806             7
13     100.0         2     8806             7
14       3.0         3     8836             3
15      81.0         3     8836             3
16      82.0         3     8836             3
17     823.0         3     8836             3
18      61.0         3     8899             3
19      79.0         3     8899             3
20    1172.0         3     8899             3
21    1174.0         3     8899             3
22      91.0         3     8901             3
23    1199.0         3     8901             3
24      97.0         3     8901             3
25    1189.0         3     8901             3
26       3.0         4     8902             9
27      68.0         3     8902             7
28     102.0         3     8902             9
29    1187.0         3     8902             7
30      12.0         1     8902             7
31      12.0         2     8903             2
32      79.0         2     8903             2
33     100.0         2     8903             2
34      28.0         2     8904             3
35    1172.0         1     8904             3
36      93.0         1     8904             3
37       3.0         7     9338             9
38      98.0         7     9338             9
39     970.0         7     9338             9
40    1192.0         7     9338             9
41      76.0         5     9338             9
42     941.0         5     9338             9
43    1187.0         5     9338             9
44      81.0         4     9338             9
45      60.0         4     9338             9
46     823.0         3     9338             9
47       3.0         6     9339             9
48      60.0         6     9339             9
49     823.0         6     9339             9
50    1181.0         5     9339             9
51      82.0         5     9339             9
52      61.0         4     9339             9
53      98.0         4     9339             9
54      93.0         4     9339             9
55    1172.0         3     9339             9
56    1184.0         3     9339             9
57     102.0         3     9340             3
58       3.0         1     9340             4
59    1187.0         1     9340             4
60    1212.0         1     9340             4
61      67.0         9     9341            12
62     102.0         8     9341            12
63    1019.0         8     9341            12
64    1179.0         7     9341            12
65      12.0         7     9341            12
66       3.0         6     9341            12
67      60.0         6     9341            12
68      61.0         6     9341            12
69    1181.0         6     9341            12
70      93.0         5     9341            12
71      74.0         5     9341            12
72      81.0         4     9341            12
73       7.0         3     9341            12
74     100.0         3     9342             5
75       3.0         2     9342             5
76    1159.0         2     9342             5
77    1187.0         2     9342             5
78      67.0         1     9342             5
79     970.0         7     9343            10
80    1172.0         6     9343            10
81     823.0         6     9343            10
82       3.0         5     9343            10
83      82.0         5     9343            10
84    1179.0         5     9343            10
85      98.0         4     9343            10
86      79.0         3     9343            10
87       7.0         2     9343            10
88      81.0         2     9343            10
89      93.0         1     9343            10
90      97.0         4    11895             4
91     970.0         4    11895             4
92    1172.0         4    11895             4
93      82.0         3    11895             4
94      98.0         3    11895             4
95     100.0         3    11896             4
96       3.0         2    11896             4
97    1187.0         2    11896             2
98     941.0         2    11896             3
99    1177.0         1    11896             3
100      3.0         1    11897             1
101     82.0         1    11897             1
102      3.0         2    11899             2
103     60.0         2    11899             2
104   1181.0         2    11899             2
105    941.0         1    12002             3
106   1159.0         1    12002             3
107      3.0         2    12003             3
108     98.0         2    12003             3
109     82.0         1    12003             3
110     12.0         1    12003             3
111     61.0         3    17582             3
112      3.0         1    17582             3
113     82.0         1    17582             3
114   1212.0         1    17582             3

In [12]:
test2 = filtered_pairs[filtered_pairs["site_id"] == 8806]
test2.to_csv("test2")

In [13]:
# Step 1: Group by site and calculate the required values
def calculate_expected_per_site(df):
    # Group by site_id
    results = []

    for site_id, group in df.groupby('site_id'):
        # Step 1: Calculate total raw expected counts for the site
        total_raw_expected = group['raw_expected'].sum()

        # Step 2: Calculate the proportion of unique pairings for each species in the site
        group['proportion'] = group['raw_expected'] / total_raw_expected

        # Step 3: Scale the proportions to match the total observed significant pairings
        total_observed = group['observed'].sum()
        group['expected'] = group['proportion'] * total_observed

        # Append the updated group to results
        results.append(group)

    # Combine the updated groups back into a single DataFrame
    return pd.concat(results)

# Apply the function to calculate per-site expected values
merged_results_with_expected = calculate_expected_per_site(merged_results)

# Display the updated DataFrame
pd.set_option('display.max_rows', None)  # Show all rows
print(merged_results_with_expected)

     species  observed  site_id  raw_expected  proportion  expected
0     1172.0         5     8182             5    0.166667  4.000000
1       93.0         5     8182             5    0.166667  4.000000
2        3.0         4     8182             5    0.166667  4.000000
3      102.0         4     8182             5    0.166667  4.000000
4     1174.0         4     8182             5    0.166667  4.000000
5       28.0         2     8182             5    0.166667  4.000000
6       81.0         6     8806             7    0.125000  4.250000
7       12.0         5     8806             7    0.125000  4.250000
8      823.0         5     8806             7    0.125000  4.250000
9     1192.0         5     8806             7    0.125000  4.250000
10      82.0         4     8806             7    0.125000  4.250000
11      61.0         4     8806             7    0.125000  4.250000
12       3.0         3     8806             7    0.125000  4.250000
13     100.0         2     8806             7    0.125000  4.250000
14       3.0         3     8836             3    0.250000  3.000000
15      81.0         3     8836             3    0.250000  3.000000
16      82.0         3     8836             3    0.250000  3.000000
17     823.0         3     8836             3    0.250000  3.000000
18      61.0         3     8899             3    0.250000  3.000000
19      79.0         3     8899             3    0.250000  3.000000
20    1172.0         3     8899             3    0.250000  3.000000
21    1174.0         3     8899             3    0.250000  3.000000
22      91.0         3     8901             3    0.250000  3.000000
23    1199.0         3     8901             3    0.250000  3.000000
24      97.0         3     8901             3    0.250000  3.000000
25    1189.0         3     8901             3    0.250000  3.000000
26       3.0         4     8902             9    0.230769  3.230769
27      68.0         3     8902             7    0.179487  2.512821
28     102.0         3     8902             9    0.230769  3.230769
29    1187.0         3     8902             7    0.179487  2.512821
30      12.0         1     8902             7    0.179487  2.512821
31      12.0         2     8903             2    0.333333  2.000000
32      79.0         2     8903             2    0.333333  2.000000
33     100.0         2     8903             2    0.333333  2.000000
34      28.0         2     8904             3    0.333333  1.333333
35    1172.0         1     8904             3    0.333333  1.333333
36      93.0         1     8904             3    0.333333  1.333333
37       3.0         7     9338             9    0.100000  5.400000
38      98.0         7     9338             9    0.100000  5.400000
39     970.0         7     9338             9    0.100000  5.400000
40    1192.0         7     9338             9    0.100000  5.400000
41      76.0         5     9338             9    0.100000  5.400000
42     941.0         5     9338             9    0.100000  5.400000
43    1187.0         5     9338             9    0.100000  5.400000
44      81.0         4     9338             9    0.100000  5.400000
45      60.0         4     9338             9    0.100000  5.400000
46     823.0         3     9338             9    0.100000  5.400000
47       3.0         6     9339             9    0.100000  4.600000
48      60.0         6     9339             9    0.100000  4.600000
49     823.0         6     9339             9    0.100000  4.600000
50    1181.0         5     9339             9    0.100000  4.600000
51      82.0         5     9339             9    0.100000  4.600000
52      61.0         4     9339             9    0.100000  4.600000
53      98.0         4     9339             9    0.100000  4.600000
54      93.0         4     9339             9    0.100000  4.600000
55    1172.0         3     9339             9    0.100000  4.600000
56    1184.0         3     9339             9    0.100000  4.600000
57     102.0         3     9340             3    0.200000  1.200000
58       3.0         1     9340             4    0.266667  1.600000
59    1187.0         1     9340             4    0.266667  1.600000
60    1212.0         1     9340             4    0.266667  1.600000
61      67.0         9     9341            12    0.076923  6.153846
62     102.0         8     9341            12    0.076923  6.153846
63    1019.0         8     9341            12    0.076923  6.153846
64    1179.0         7     9341            12    0.076923  6.153846
65      12.0         7     9341            12    0.076923  6.153846
66       3.0         6     9341            12    0.076923  6.153846
67      60.0         6     9341            12    0.076923  6.153846
68      61.0         6     9341            12    0.076923  6.153846
69    1181.0         6     9341            12    0.076923  6.153846
70      93.0         5     9341            12    0.076923  6.153846
71      74.0         5     9341            12    0.076923  6.153846
72      81.0         4     9341            12    0.076923  6.153846
73       7.0         3     9341            12    0.076923  6.153846
74     100.0         3     9342             5    0.200000  2.000000
75       3.0         2     9342             5    0.200000  2.000000
76    1159.0         2     9342             5    0.200000  2.000000
77    1187.0         2     9342             5    0.200000  2.000000
78      67.0         1     9342             5    0.200000  2.000000
79     970.0         7     9343            10    0.090909  4.181818
80    1172.0         6     9343            10    0.090909  4.181818
81     823.0         6     9343            10    0.090909  4.181818
82       3.0         5     9343            10    0.090909  4.181818
83      82.0         5     9343            10    0.090909  4.181818
84    1179.0         5     9343            10    0.090909  4.181818
85      98.0         4     9343            10    0.090909  4.181818
86      79.0         3     9343            10    0.090909  4.181818
87       7.0         2     9343            10    0.090909  4.181818
88      81.0         2     9343            10    0.090909  4.181818
89      93.0         1     9343            10    0.090909  4.181818
90      97.0         4    11895             4    0.200000  3.600000
91     970.0         4    11895             4    0.200000  3.600000
92    1172.0         4    11895             4    0.200000  3.600000
93      82.0         3    11895             4    0.200000  3.600000
94      98.0         3    11895             4    0.200000  3.600000
95     100.0         3    11896             4    0.250000  2.500000
96       3.0         2    11896             4    0.250000  2.500000
97    1187.0         2    11896             2    0.125000  1.250000
98     941.0         2    11896             3    0.187500  1.875000
99    1177.0         1    11896             3    0.187500  1.875000
100      3.0         1    11897             1    0.500000  1.000000
101     82.0         1    11897             1    0.500000  1.000000
102      3.0         2    11899             2    0.333333  2.000000
103     60.0         2    11899             2    0.333333  2.000000
104   1181.0         2    11899             2    0.333333  2.000000
105    941.0         1    12002             3    0.500000  1.000000
106   1159.0         1    12002             3    0.500000  1.000000
107      3.0         2    12003             3    0.250000  1.500000
108     98.0         2    12003             3    0.250000  1.500000
109     82.0         1    12003             3    0.250000  1.500000
110     12.0         1    12003             3    0.250000  1.500000
111     61.0         3    17582             3    0.250000  1.500000
112      3.0         1    17582             3    0.250000  1.500000
113     82.0         1    17582             3    0.250000  1.500000
114   1212.0         1    17582             3    0.250000  1.500000

In [14]:
from scipy.stats import chisquare

# Step 1: Function to calculate chi-square per site
def calculate_chi_square_per_site(df):
    results = []

    for site_id, group in df.groupby('site_id'):
        # Step 1.1: Calculate chi-square contribution for each species in the site
        group['chi_square_contribution'] = (
            (group['observed'] - group['expected']) ** 2 / group['expected']
        )

        # Step 1.2: Calculate overall chi-square statistic and p-value for the site
        chi_square_stat = group['chi_square_contribution'].sum()
        degrees_of_freedom = len(group) - 1  # Number of species - 1
        chi_square_results = chisquare(
            f_obs=group['observed'], 
            f_exp=group['expected']
        )
        p_value = chi_square_results.pvalue

        # Step 1.3: Add site-level results to the group
        group['chi_square_stat'] = chi_square_stat
        group['degrees_of_freedom'] = degrees_of_freedom
        group['p_value'] = p_value

        # Append the updated group to results
        results.append(group)

    # Combine all site-level DataFrames
    return pd.concat(results)

# Step 2: Apply the function to calculate per-site chi-square statistics
merged_results_with_chi_square = calculate_chi_square_per_site(merged_results_with_expected)

# Step 3: Display the updated DataFrame with per-site chi-square results
pd.set_option('display.max_rows', None)  # Show all rows
merged_results_with_chi_square

,species,observed,site_id,raw_expected,proportion,expected,chi_square_contribution,chi_square_stat,degrees_of_freedom,p_value
0,1172.0,5,8182,5,0.166667,4.000000,0.250000,1.500000,5,0.913070
1,93.0,5,8182,5,0.166667,4.000000,0.250000,1.500000,5,0.913070
2,3.0,4,8182,5,0.166667,4.000000,0.000000,1.500000,5,0.913070
3,102.0,4,8182,5,0.166667,4.000000,0.000000,1.500000,5,0.913070
4,1174.0,4,8182,5,0.166667,4.000000,0.000000,1.500000,5,0.913070
5,28.0,2,8182,5,0.166667,4.000000,1.000000,1.500000,5,0.913070
6,81.0,6,8806,7,0.125000,4.250000,0.720588,2.705882,7,0.910813
7,12.0,5,8806,7,0.125000,4.250000,0.132353,2.705882,7,0.910813
8,823.0,5,8806,7,0.125000,4.250000,0.132353,2.705882,7,0.910813
9,1192.0,5,8806,7,0.125000,4.250000,0.132353,2.705882,7,0.910813
10,82.0,4,8806,7,0.125000,4.250000,0.014706,2.705882,7,0.910813
11,61.0,4,8806,7,0.125000,4.250000,0.014706,2.705882,7,0.910813
12,3.0,3,8806,7,0.125000,4.250000,0.367647,2.705882,7,0.910813
13,100.0,2,8806,7,0.125000,4.250000,1.191176,2.705882,7,0.910813
14,3.0,3,8836,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
15,81.0,3,8836,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
16,82.0,3,8836,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
17,823.0,3,8836,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
18,61.0,3,8899,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
19,79.0,3,8899,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
20,1172.0,3,8899,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
21,1174.0,3,8899,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
22,91.0,3,8901,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
23,1199.0,3,8901,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
24,97.0,3,8901,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
25,1189.0,3,8901,3,0.250000,3.000000,0.000000,0.000000,3,1.000000
26,3.0,4,8902,9,0.230769,3.230769,0.183150,1.299320,4,0.861491
27,68.0,3,8902,7,0.179487,2.512821,0.094453,1.299320,4,0.861491
28,102.0,3,8902,9,0.230769,3.230769,0.016484,1.299320,4,0.861491
29,1187.0,3,8902,7,0.179487,2.512821,0.094453,1.299320,4,0.861491
30,12.0,1,8902,7,0.179487,2.512821,0.910780,1.299320,4,0.861491
31,12.0,2,8903,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
32,79.0,2,8903,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
33,100.0,2,8903,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
34,28.0,2,8904,3,0.333333,1.333333,0.333333,0.500000,2,0.778801
35,1172.0,1,8904,3,0.333333,1.333333,0.083333,0.500000,2,0.778801
36,93.0,1,8904,3,0.333333,1.333333,0.083333,0.500000,2,0.778801
37,3.0,7,9338,9,0.100000,5.400000,0.474074,3.777778,9,0.925420
38,98.0,7,9338,9,0.100000,5.400000,0.474074,3.777778,9,0.925420
39,970.0,7,9338,9,0.100000,5.400000,0.474074,3.777778,9,0.925420
40,1192.0,7,9338,9,0.100000,5.400000,0.474074,3.777778,9,0.925420
41,76.0,5,9338,9,0.100000,5.400000,0.029630,3.777778,9,0.925420
42,941.0,5,9338,9,0.100000,5.400000,0.029630,3.777778,9,0.925420
43,1187.0,5,9338,9,0.100000,5.400000,0.029630,3.777778,9,0.925420
44,81.0,4,9338,9,0.100000,5.400000,0.362963,3.777778,9,0.925420
45,60.0,4,9338,9,0.100000,5.400000,0.362963,3.777778,9,0.925420
46,823.0,3,9338,9,0.100000,5.400000,1.066667,3.777778,9,0.925420
47,3.0,6,9339,9,0.100000,4.600000,0.426087,2.695652,9,0.975151
48,60.0,6,9339,9,0.100000,4.600000,0.426087,2.695652,9,0.975151
49,823.0,6,9339,9,0.100000,4.600000,0.426087,2.695652,9,0.975151
50,1181.0,5,9339,9,0.100000,4.600000,0.034783,2.695652,9,0.975151
51,82.0,5,9339,9,0.100000,4.600000,0.034783,2.695652,9,0.975151
52,61.0,4,9339,9,0.100000,4.600000,0.078261,2.695652,9,0.975151
53,98.0,4,9339,9,0.100000,4.600000,0.078261,2.695652,9,0.975151
54,93.0,4,9339,9,0.100000,4.600000,0.078261,2.695652,9,0.975151
55,1172.0,3,9339,9,0.100000,4.600000,0.556522,2.695652,9,0.975151
56,1184.0,3,9339,9,0.100000,4.600000,0.556522,2.695652,9,0.975151
57,102.0,3,9340,3,0.200000,1.200000,2.700000,3.375000,3,0.337340
58,3.0,1,9340,4,0.266667,1.600000,0.225000,3.375000,3,0.337340
59,1187.0,1,9340,4,0.266667,1.600000,0.225000,3.375000,3,0.337340
60,1212.0,1,9340,4,0.266667,1.600000,0.225000,3.375000,3,0.337340
61,67.0,9,9341,12,0.076923,6.153846,1.316346,5.475000,12,0.940207
62,102.0,8,9341,12,0.076923,6.153846,0.553846,5.475000,12,0.940207
63,1019.0,8,9341,12,0.076923,6.153846,0.553846,5.475000,12,0.940207
64,1179.0,7,9341,12,0.076923,6.153846,0.116346,5.475000,12,0.940207
65,12.0,7,9341,12,0.076923,6.153846,0.116346,5.475000,12,0.940207
66,3.0,6,9341,12,0.076923,6.153846,0.003846,5.475000,12,0.940207
67,60.0,6,9341,12,0.076923,6.153846,0.003846,5.475000,12,0.940207
68,61.0,6,9341,12,0.076923,6.153846,0.003846,5.475000,12,0.940207
69,1181.0,6,9341,12,0.076923,6.153846,0.003846,5.475000,12,0.940207
70,93.0,5,9341,12,0.076923,6.153846,0.216346,5.475000,12,0.940207
71,74.0,5,9341,12,0.076923,6.153846,0.216346,5.475000,12,0.940207
72,81.0,4,9341,12,0.076923,6.153846,0.753846,5.475000,12,0.940207
73,7.0,3,9341,12,0.076923,6.153846,1.616346,5.475000,12,0.940207
74,100.0,3,9342,5,0.200000,2.000000,0.500000,1.000000,4,0.909796
75,3.0,2,9342,5,0.200000,2.000000,0.000000,1.000000,4,0.909796
76,1159.0,2,9342,5,0.200000,2.000000,0.000000,1.000000,4,0.909796
77,1187.0,2,9342,5,0.200000,2.000000,0.000000,1.000000,4,0.909796
78,67.0,1,9342,5,0.200000,2.000000,0.500000,1.000000,4,0.909796
79,970.0,7,9343,10,0.090909,4.181818,1.899209,9.000000,10,0.532104
80,1172.0,6,9343,10,0.090909,4.181818,0.790514,9.000000,10,0.532104
81,823.0,6,9343,10,0.090909,4.181818,0.790514,9.000000,10,0.532104
82,3.0,5,9343,10,0.090909,4.181818,0.160079,9.000000,10,0.532104
83,82.0,5,9343,10,0.090909,4.181818,0.160079,9.000000,10,0.532104
84,1179.0,5,9343,10,0.090909,4.181818,0.160079,9.000000,10,0.532104
85,98.0,4,9343,10,0.090909,4.181818,0.007905,9.000000,10,0.532104
86,79.0,3,9343,10,0.090909,4.181818,0.333992,9.000000,10,0.532104
87,7.0,2,9343,10,0.090909,4.181818,1.138340,9.000000,10,0.532104
88,81.0,2,9343,10,0.090909,4.181818,1.138340,9.000000,10,0.532104
89,93.0,1,9343,10,0.090909,4.181818,2.420949,9.000000,10,0.532104
90,97.0,4,11895,4,0.200000,3.600000,0.044444,0.333333,4,0.987562
91,970.0,4,11895,4,0.200000,3.600000,0.044444,0.333333,4,0.987562
92,1172.0,4,11895,4,0.200000,3.600000,0.044444,0.333333,4,0.987562
93,82.0,3,11895,4,0.200000,3.600000,0.100000,0.333333,4,0.987562
94,98.0,3,11895,4,0.200000,3.600000,0.100000,0.333333,4,0.987562
95,100.0,3,11896,4,0.250000,2.500000,0.100000,1.066667,4,0.899524
96,3.0,2,11896,4,0.250000,2.500000,0.100000,1.066667,4,0.899524
97,1187.0,2,11896,2,0.125000,1.250000,0.450000,1.066667,4,0.899524
98,941.0,2,11896,3,0.187500,1.875000,0.008333,1.066667,4,0.899524
99,1177.0,1,11896,3,0.187500,1.875000,0.408333,1.066667,4,0.899524
100,3.0,1,11897,1,0.500000,1.000000,0.000000,0.000000,1,1.000000
101,82.0,1,11897,1,0.500000,1.000000,0.000000,0.000000,1,1.000000
102,3.0,2,11899,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
103,60.0,2,11899,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
104,1181.0,2,11899,2,0.333333,2.000000,0.000000,0.000000,2,1.000000
105,941.0,1,12002,3,0.500000,1.000000,0.000000,0.000000,1,1.000000
106,1159.0,1,12002,3,0.500000,1.000000,0.000000,0.000000,1,1.000000
107,3.0,2,12003,3,0.250000,1.500000,0.166667,0.666667,3,0.881015
108,98.0,2,12003,3,0.250000,1.500000,0.166667,0.666667,3,0.881015
109,82.0,1,12003,3,0.250000,1.500000,0.166667,0.666667,3,0.881015
110,12.0,1,12003,3,0.250000,1.500000,0.166667,0.666667,3,0.881015
111,61.0,3,17582,3,0.250000,1.500000,1.500000,2.000000,3,0.572407
112,3.0,1,17582,3,0.250000,1.500000,0.166667,2.000000,3,0.572407
113,82.0,1,17582,3,0.250000,1.500000,0.166667,2.000000,3,0.572407
114,1212.0,1,17582,3,0.250000,1.500000,0.166667,2.000000,3,0.572407

In [30]:
merged_results_with_chi_square['site_id'].unique()

array([ 8182,  8806,  8836,  8899,  8901,  8902,  8903,  8904,  9338,
        9339,  9340,  9341,  9342,  9343, 11895, 11896, 11897, 11899,
       12002, 12003, 17582])